In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("winequalityN.csv")
data.head()

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,white,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,white,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [4]:
data = data.drop("type", axis=1)

In [5]:
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [21]:
data["urta_arif"] = data.T.mean()

In [22]:
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,urta_arif
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6,20.202000
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6,13.451769
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6,12.578854
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6,20.753354
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6,20.753354

In [4]:
data.value_counts()

type   fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  free sulfur dioxide  total sulfur dioxide  density   pH    sulphates  alcohol  quality
white  7.0            0.15              0.28         14.7            0.051      29.0                 149.0                 0.997920  2.96  0.39       9.0      7          8
       7.3            0.19              0.27         13.9            0.057      45.0                 155.0                 0.998070  2.94  0.41       8.8      8          8
       7.4            0.16              0.30         13.7            0.056      33.0                 168.0                 0.998250  2.90  0.44       8.7      7          7
       6.8            0.18              0.30         12.8            0.062      19.0                 171.0                 0.998080  3.00  0.52       9.0      7          7
       7.4            0.16              0.27         15.5            0.050      25.0                 135.0                 0.998400  2.90  0.43       8.7      7          6
                                                                                                                                                                         ..
       6.0            0.20              0.26         14.7            0.045      53.0                 125.0                 0.998365  2.99  0.69       9.4      6          1
                                                     1.1             0.033      38.0                 67.0                  0.989540  3.14  0.38       11.5     6          1
                                        0.25         2.0             0.041      30.0                 95.0                  0.990780  3.27  0.56       11.1     6          1
                                        0.24         5.3             0.075      49.0                 201.0                 0.994660  3.21  0.43       9.5      5          1
       14.2           0.27              0.49         1.1             0.037      33.0                 156.0                 0.992000  3.15  0.54       11.1     6          1
Length: 5295, dtype: int64